line isnt working
Assets\Scripts\keys\KeyRaycast.cs(14,17): error CS0246: The type or namespace name 'KeyItemController' could not be found (are you missing a using directive or an assembly reference?)

it 2 am so im losing my mind this scipt should work and if doesnt i will cry